language: android
android:
  components:
    - build-tools-28.0.2
    - android-27
    - extra
  licenses:
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

script:
  - ./gradlew build :plugin:jacocoTestReport -s --info

after_success:
  - bash <(curl -s https://codecov.io/bash)

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
